//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renaissance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int postId { get; set; }
        public string body { get; set; }
        public string tag { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
