//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renaissance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int questionId { get; set; }
        public int userId { get; set; }
        public string Body { get; set; }
        public string Title { get; set; }
        public string Tag { get; set; }
        public string Answer { get; set; }
        public string Options { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
